### ISSUE TITLE
error: could not compile `NyxInvoke` (bin "NyxInvoke")

### ISSUE THREAD

**Issue by johnjohnsp1** [BlackSnufkin/NyxInvoke#1]
Hi,
thanks for sharing the code, trying to compile with provided command

PS C:\temp\NyxInvoke> cargo +nightly build --release --target=x86_64-pc-windows-msvc --features exe --bin NyxInvoke
   Compiling NyxInvoke v0.3.1 (C:\temp\NyxInvoke)
error[E0433]: failed to resolve: use of undeclared type `Path`
   --> src\common.rs:933:27
    |
933 |         if !is_remote && !Path::new(&script_path).exists() {
    |                           ^^^^ use of undeclared type `Path`
    |
help: consider importing this struct
    |
3   + use std::path::Path;
    |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `NyxInvoke` (bin "NyxInvoke") due to 1 previous error

running on windows 10 22H2 build 19045
cargo 1.80.0-nightly (4de0094ac 2024-05-09)

did something wrong or miss anything ?
thanks in advice

**Comment by BlackSnufkin** [comment]
There was a missing dependency it been fixed
